# Generated by Django 2.2.12 on 2020-05-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.Skill'),
        ),
    ]
