# Generated by Django 2.2.12 on 2020-05-30 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_auto_20200530_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employee_queue',
            field=models.ManyToManyField(related_name='employee_queue', to=settings.AUTH_USER_MODEL),
        ),
    ]
