# Generated by Django 2.2.12 on 2020-05-30 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_employee_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employee_queue',
            field=models.ManyToManyField(blank=True, related_name='employee_queue', to=settings.AUTH_USER_MODEL),
        ),
    ]
